import { CodeResponse } from '../types';

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export async function generateMockResponse(prompt: string): Promise<CodeResponse> {
  // Simulate API delay
  await delay(1000);

  // Mock response based on prompt
  const response: CodeResponse = {
    code: `// Generated code based on: ${prompt}\n\nfunction example() {\n  console.log("Hello from LlamaCoder!");\n}`,
    explanation: "Here's a simple example implementation. In a real application, this would be generated by an AI model."
  };

  return response;
}